server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
  datasource:
    password: root
    username: root
    url: jdbc:h2:mem:testdb
    datasource:
      driver-class-name: org.h2.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          show_sql: false
          format_sql: true
          use_sql_comments: true
      hibernate:
        ddl-auto: create
      generate-ddl: true

#logging:
#  file:
#    name: logs/app.log
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"
